apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
 name: vault-database
 namespace: myapp1
spec:
 provider: vault
 parameters:
   roleName: "csi"
   vaultAddress: "http://vault.vault:8200"
   # vaultNamespace: <name of Vault Namespace>
   # vaultCACertPath: <path to CA file for validation>
   # vaultTLSClientCertPath: <path to client cert>
   # vaultTLSClientKeyPath: <path to client key>
   objects: |
     - objectName: "password"
       secretPath: "secret/data/db-pass"
       secretKey: "password"
